/**
 * Pan-India Vande Bharat Express & Sleeper Explorer Engine
 *
 * Integrates with erail.in live network APIs to fetch real-time train schedules,
 * intermediate route halts, and seat/fare tables across all premier Vande Bharat corridors.
 */

export interface VandeBharatRouteSummary {
  trainNo: string;
  returnTrainNo: string;
  name: string;
  fromCode: string;
  fromCity: string;
  toCode: string;
  toCity: string;
  region: "NORTH" | "WEST" | "SOUTH" | "EAST" | "CENTRAL";
  distanceKm: number;
  typicalDuration: string;
  depTime: string;
  arrTime: string;
  runsOnDays: string; // e.g. "Except Thu" or "Daily" or "Except Wed"
  avgSpeedKmph: number;
  topSpeedKmph: number;
  regularExpressDuration: string;
  hoursSaved: string;
  fareCCEstimate: number;
  fareECEstimate: number;
  cateringCharge: number;
  highlightTag: string;
}

export const VANDE_BHARAT_CATALOGUE: VandeBharatRouteSummary[] = [
  {
    trainNo: "22436",
    returnTrainNo: "22435",
    name: "New Delhi - Varanasi Vande Bharat",
    fromCode: "NDLS",
    fromCity: "New Delhi",
    toCode: "BSB",
    toCity: "Varanasi",
    region: "NORTH",
    distanceKm: 759,
    typicalDuration: "8h 00m",
    depTime: "06:00",
    arrTime: "14:00",
    runsOnDays: "Except Mon, Thu",
    avgSpeedKmph: 95,
    topSpeedKmph: 130,
    regularExpressDuration: "12h 45m",
    hoursSaved: "4h 45m",
    fareCCEstimate: 1838,
    fareECEstimate: 3388,
    cateringCharge: 390,
    highlightTag: "India's Flagship Vande Bharat",
  },
  {
    trainNo: "22439",
    returnTrainNo: "22440",
    name: "New Delhi - Katra Vande Bharat",
    fromCode: "NDLS",
    fromCity: "New Delhi",
    toCode: "SVDK",
    toCity: "Katra (Vaishno Devi)",
    region: "NORTH",
    distanceKm: 655,
    typicalDuration: "8h 00m",
    depTime: "06:00",
    arrTime: "14:00",
    runsOnDays: "Except Tue",
    avgSpeedKmph: 82,
    topSpeedKmph: 130,
    regularExpressDuration: "12h 15m",
    hoursSaved: "4h 15m",
    fareCCEstimate: 1665,
    fareECEstimate: 3055,
    cateringCharge: 390,
    highlightTag: "Pilgrim High Speed Corridor",
  },
  {
    trainNo: "20901",
    returnTrainNo: "20902",
    name: "Mumbai Central - Gandhinagar Vande Bharat",
    fromCode: "MMCT",
    fromCity: "Mumbai",
    toCode: "GNC",
    toCity: "Gandhinagar / Ahmedabad",
    region: "WEST",
    distanceKm: 521,
    typicalDuration: "6h 15m",
    depTime: "06:00",
    arrTime: "12:15",
    runsOnDays: "Except Sun",
    avgSpeedKmph: 85,
    topSpeedKmph: 130,
    regularExpressDuration: "8h 50m",
    hoursSaved: "2h 35m",
    fareCCEstimate: 1420,
    fareECEstimate: 2630,
    cateringCharge: 320,
    highlightTag: "Business Trunk Corridor",
  },
  {
    trainNo: "20607",
    returnTrainNo: "20608",
    name: "Chennai - Mysuru Vande Bharat",
    fromCode: "MAS",
    fromCity: "Chennai",
    toCode: "MYS",
    toCity: "Mysuru / Bengaluru",
    region: "SOUTH",
    distanceKm: 497,
    typicalDuration: "6h 30m",
    depTime: "05:50",
    arrTime: "12:20",
    runsOnDays: "Except Wed",
    avgSpeedKmph: 76,
    topSpeedKmph: 130,
    regularExpressDuration: "9h 15m",
    hoursSaved: "2h 45m",
    fareCCEstimate: 1365,
    fareECEstimate: 2485,
    cateringCharge: 320,
    highlightTag: "South India's First Vande Bharat",
  },
  {
    trainNo: "22301",
    returnTrainNo: "22302",
    name: "Howrah - New Jalpaiguri Vande Bharat",
    fromCode: "HWH",
    fromCity: "Kolkata (Howrah)",
    toCode: "NJP",
    toCity: "New Jalpaiguri (Siliguri)",
    region: "EAST",
    distanceKm: 561,
    typicalDuration: "7h 30m",
    depTime: "05:55",
    arrTime: "13:25",
    runsOnDays: "Except Wed",
    avgSpeedKmph: 75,
    topSpeedKmph: 130,
    regularExpressDuration: "10h 30m",
    hoursSaved: "3h 00m",
    fareCCEstimate: 1565,
    fareECEstimate: 2825,
    cateringCharge: 350,
    highlightTag: "North Bengal Lifeline",
  },
  {
    trainNo: "20833",
    returnTrainNo: "20834",
    name: "Visakhapatnam - Secunderabad Vande Bharat",
    fromCode: "VSKP",
    fromCity: "Visakhapatnam",
    toCode: "SC",
    toCity: "Hyderabad (Secunderabad)",
    region: "SOUTH",
    distanceKm: 699,
    typicalDuration: "8h 30m",
    depTime: "05:45",
    arrTime: "14:15",
    runsOnDays: "Except Sun",
    avgSpeedKmph: 82,
    topSpeedKmph: 130,
    regularExpressDuration: "12h 00m",
    hoursSaved: "3h 30m",
    fareCCEstimate: 1720,
    fareECEstimate: 3170,
    cateringCharge: 380,
    highlightTag: "Andhra-Telangana Connector",
  },
  {
    trainNo: "20171",
    returnTrainNo: "20172",
    name: "Rani Kamlapati - Hazrat Nizamuddin Vande Bharat",
    fromCode: "RKMP",
    fromCity: "Bhopal (Rani Kamlapati)",
    toCode: "NZM",
    toCity: "Delhi (Nizamuddin)",
    region: "CENTRAL",
    distanceKm: 701,
    typicalDuration: "7h 36m",
    depTime: "05:40",
    arrTime: "13:16",
    runsOnDays: "Except Sat",
    avgSpeedKmph: 92,
    topSpeedKmph: 160,
    regularExpressDuration: "10h 45m",
    hoursSaved: "3h 09m",
    fareCCEstimate: 1735,
    fareECEstimate: 3185,
    cateringCharge: 380,
    highlightTag: "Fastest 160 km/h Section (Agra-Delhi)",
  },
  {
    trainNo: "22426",
    returnTrainNo: "22425",
    name: "Anand Vihar - Ayodhya Dham Vande Bharat",
    fromCode: "ANVT",
    fromCity: "Delhi (Anand Vihar)",
    toCode: "AY",
    toCity: "Ayodhya Dham",
    region: "NORTH",
    distanceKm: 628,
    typicalDuration: "8h 20m",
    depTime: "06:10",
    arrTime: "14:30",
    runsOnDays: "Except Wed",
    avgSpeedKmph: 75,
    topSpeedKmph: 130,
    regularExpressDuration: "11h 15m",
    hoursSaved: "2h 55m",
    fareCCEstimate: 1625,
    fareECEstimate: 2965,
    cateringCharge: 360,
    highlightTag: "Direct Ram Mandir Express",
  },
  {
    trainNo: "20701",
    returnTrainNo: "20702",
    name: "Mumbai CSMT - Sainagar Shirdi Vande Bharat",
    fromCode: "CSMT",
    fromCity: "Mumbai CSMT",
    toCode: "SNSI",
    toCity: "Shirdi",
    region: "WEST",
    distanceKm: 343,
    typicalDuration: "5h 20m",
    depTime: "06:20",
    arrTime: "11:40",
    runsOnDays: "Except Tue",
    avgSpeedKmph: 64,
    topSpeedKmph: 110,
    regularExpressDuration: "9h 00m",
    hoursSaved: "3h 40m",
    fareCCEstimate: 975,
    fareECEstimate: 1840,
    cateringCharge: 260,
    highlightTag: "Thal Ghat Gradient Tech (Zero Banker Loco)",
  },
  {
    trainNo: "20643",
    returnTrainNo: "20644",
    name: "Chennai - Coimbatore Vande Bharat",
    fromCode: "MAS",
    fromCity: "Chennai",
    toCode: "CBE",
    toCity: "Coimbatore",
    region: "SOUTH",
    distanceKm: 495,
    typicalDuration: "5h 50m",
    depTime: "06:10",
    arrTime: "12:00",
    runsOnDays: "Except Wed",
    avgSpeedKmph: 85,
    topSpeedKmph: 130,
    regularExpressDuration: "8h 15m",
    hoursSaved: "2h 25m",
    fareCCEstimate: 1365,
    fareECEstimate: 2490,
    cateringCharge: 310,
    highlightTag: "Industrial Hub Link",
  },
  {
    trainNo: "22347",
    returnTrainNo: "22348",
    name: "Howrah - Patna Vande Bharat",
    fromCode: "HWH",
    fromCity: "Kolkata (Howrah)",
    toCode: "PNBE",
    toCity: "Patna",
    region: "EAST",
    distanceKm: 532,
    typicalDuration: "6h 35m",
    depTime: "05:55",
    arrTime: "12:30",
    runsOnDays: "Except Wed",
    avgSpeedKmph: 81,
    topSpeedKmph: 130,
    regularExpressDuration: "9h 30m",
    hoursSaved: "2h 55m",
    fareCCEstimate: 1450,
    fareECEstimate: 2675,
    cateringCharge: 330,
    highlightTag: "Bengal-Bihar High Speed Link",
  },
  {
    trainNo: "20661",
    returnTrainNo: "20662",
    name: "Bengaluru - Kacheguda Vande Bharat",
    fromCode: "SBC",
    fromCity: "Bengaluru (Yesvantpur)",
    toCode: "KCG",
    toCity: "Hyderabad (Kacheguda)",
    region: "SOUTH",
    distanceKm: 610,
    typicalDuration: "8h 15m",
    depTime: "05:45",
    arrTime: "14:00",
    runsOnDays: "Except Wed",
    avgSpeedKmph: 74,
    topSpeedKmph: 130,
    regularExpressDuration: "11h 30m",
    hoursSaved: "3h 15m",
    fareCCEstimate: 1540,
    fareECEstimate: 2790,
    cateringCharge: 350,
    highlightTag: "Silicon Corridor Tech Link",
  },
];

export interface VandeBharatSleeperSpec {
  feature: string;
  vandeBharatSleeper: string;
  traditionalRajdhani: string;
  travelerBenefit: string;
}

export const SLEEPER_COMPARISON_SPECS: VandeBharatSleeperSpec[] = [
  {
    feature: "Operating Speed",
    vandeBharatSleeper: "160 km/h operational capability",
    traditionalRajdhani: "130 km/h max locomotive limit",
    travelerBenefit: "Cuts Delhi-Mumbai and Delhi-Kolkata journeys by 2 to 3 hours.",
  },
  {
    feature: "Coupler & Ride Quality",
    vandeBharatSleeper: "Semi-permanent tightlock couplers (Jerk-Free)",
    traditionalRajdhani: "Standard CBC couplers with noticeable starting jerks",
    travelerBenefit: "No sleep interruptions during train braking or acceleration.",
  },
  {
    feature: "Berth Ergonomics",
    vandeBharatSleeper: "Cushioned memory-foam mattress with footrests",
    traditionalRajdhani: "Standard synthetic foam rexine berths",
    travelerBenefit: "Superior lumbar support for overnight sleep.",
  },
  {
    feature: "Cabin Doors & Noise",
    vandeBharatSleeper: "Sensor-operated automated sliding soundproof doors",
    traditionalRajdhani: "Manual latch swing doors",
    travelerBenefit: "Airport-quiet cabin interior (under 65 dB).",
  },
  {
    feature: "Washroom Tech",
    vandeBharatSleeper: "Bio-vacuum toilets with sensor taps and hot water",
    traditionalRajdhani: "Gravity drop bio-toilets with cold water only",
    travelerBenefit: "Modern aircraft-style odorless hygiene with warm water in winter.",
  },
];

export interface CateringMenuCategory {
  timeWindow: string;
  mealName: string;
  vegItems: string[];
  nonVegItems: string[];
  optOutSavings: string;
}

export const CATERING_MENU: CateringMenuCategory[] = [
  {
    timeWindow: "Morning (06:30 - 08:30)",
    mealName: "Morning Tea & Breakfast",
    vegItems: [
      "Stuffed Paratha / Upma / Idli Vada with Sambar & Coconut Chutney",
      "Fresh Fruit Juice, Cookies, and Amul Butter with Bread",
      "Tea / Coffee kit (Insta Dip with Dairy Whitener)",
    ],
    nonVegItems: [
      "2-Egg Cheese Omelette with Butter Toasts & Hash Browns",
      "Chicken Cutlets with Mustard Dip",
      "Tea / Coffee kit with Fresh Fruit Juice",
    ],
    optOutSavings: "Save ₹125 to ₹155 per passenger on ticket checkout",
  },
  {
    timeWindow: "Noon & Night (12:30 - 14:00 & 19:30 - 21:00)",
    mealName: "Executive Lunch & Dinner",
    vegItems: [
      "Paneer Makhani / Kadhai Paneer with Dal Tadka",
      "Jeera Basmati Pulao, 2 Warm Parathas / Rotis",
      "Curd (Dahi), Pickle, Salad, and Gulab Jamun / Ice Cream",
    ],
    nonVegItems: [
      "Boneless Chicken Curry / Hyderabadi Chicken Gravy with Dal",
      "Basmati Rice, 2 Warm Rotis",
      "Curd, Salad, and Branded Ice Cream Dessert",
    ],
    optOutSavings: "Save ₹245 to ₹290 per passenger on ticket checkout",
  },
  {
    timeWindow: "Evening (16:30 - 17:30)",
    mealName: "High Tea & Evening Snacks",
    vegItems: [
      "Samosa / Kachori / Veg Patties with Mint Chutney",
      "Dry Fruit Chikki / Roasted Cashews",
      "Haldiram Mixture, Frooti / Juice, and Hot Tea",
    ],
    nonVegItems: [
      "Chicken Patties / Roasted Chicken Roll",
      "Dry Fruit Packet and Fruit Juice",
      "Cookies, Haldiram Snacks, and Tea Kit",
    ],
    optOutSavings: "Save ₹105 per passenger on ticket checkout",
  },
];
